version: "3.7"

services:
  mysql:
    image: mysql:5.7.26
    volumes:
      - miniapp_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ms_root
      MYSQL_DATABASE: ms_database
      MYSQL_USER: ms_user
      MYSQL_PASSWORD: ms_password

volumes:
  miniapp_data:
    external: true
